### ISSUE TITLE
[PROPOSAL] Remove The "release" Branches

### ISSUE THREAD

**Issue by GrahamCampbell** [php-build/php-build#270]
We have tags, so we don't need a load of branches too. Was there any reason I'm missing why we have these extra branches?

**Comment by rogeriopradoj** [comment]
I think it's a good question for @CHH.

Just for comparison, https://github.com/php/php-src they maintain branches because the development is made in parallel in various of them (PHP-5.4, PHP-5.5, PHP-5.6, master), but I not sure why they maintain all the others beside these (147 branches in total today!)

**Comment by CHH** [comment]
We don't really need those branches. For a time I simply thought it might be a common occurrence that I have to bug fix a release, and I was kind of obsessed with the perfect branch setup to do that. So remove them, we can always branch away from the tag if a release has to be fixed.

**Comment by GrahamCampbell** [comment]
Done. :)

**Comment by rogeriopradoj** [comment]
:+1:
