### ISSUE TITLE
PHP 7.1 (Travis)

### ISSUE THREAD

**Issue by krakjoe** [php-build/php-build#382]
PHP 7.1 is in alpha.

I'm told support is required here for travis: https://github.com/travis-ci/travis-ci/issues/6148

**Comment by rogeriopradoj** [comment]
Hi, @krakjoe , how are you doing? I hope fine!. Let's just have https://travis-ci.org/php-build/php-build/builds/137057088 (#383) finish and we can call @BanzaiMan to move travis up, right?

PS.: I saw you have karma in https://github.com/php/php-src repo, (https://people.php.net/krakjoe). Do you mind creating the branch there named `PHP-7.1`, as the existing `PHP-7.0`, `PHP-5.6`, `PHP-5.5` etc ?

The reason is that I'm working on 7.1snapshot for php-build, as we have here at: https://github.com/php-build/php-build/tree/master/share/php-build/definitions.

Thanks in advance!
