### ISSUE TITLE
Php-fpm.sock?

### ISSUE THREAD

**Issue by bes1002t** [php-build/php-build#472]
Hi,

I built php 7.1.8 with php-build. Now I want to setup an nginx server but it expects a /var/run/php.7.0-fpm.sock file. I thought maybe the newer file is in .phpenv/versions/7.1.8/var/run but this directory is empty. Is there a task I should do that builds this file or is it somewhere else located?

**Comment by madumlao** [comment]
#529 now additionally gives the PHP default setting for the listening socket as `127.0.0.1:9000`, which is the default setting provided by `php-fpm.conf` given by PHP.

`php-fpm.conf` should now be found in your `$HOME/.phpenv/versions/$VERSION/etc/` if built from PHP, or otherwise in your `$PREFIX/etc`.
