### ISSUE TITLE
Better Command Line Opt Parsing

### ISSUE THREAD

**Issue by CHH** [php-build/php-build#53]
Make a better opt parsing, so all options can be supplied in any order.

**Comment by gerardroche** [comment]
Should I redo this.

### Pros
 
- One value of better parsing options is that options can be given in any order.


*Deprecated means it may emit a log notice and will be removed in v2.0*

### Questions:

- Should arguments be deprecated in favour of options? i.e. instead of  `php-build <definition> <prefix>` have  `php-build --definition <definition> --prefix <prefix>`

  Or provide alternative options for arguments? i.e. all of these are equavilant:

    - `php-build --definition <definition> --prefix <prefix>` (preferred)
    - `php-build <definition> <prefix>`
    - `php-build <definition> --prefix <prefix>` 
    - `php-build --prefix <prefix> <definition>` 
    - `php-build --definition <definition> <prefix>`
    - `php-build  <prefix> --definition <definition>`

  One reason I think arguments should be deprecated is I tend to forget which order they are in: `php-build <definition> <prefix>` or `php-build <prefix> <definition>`. With the option parsing described above this isn't as big an issue because either both arguments or just one need be given as an option e.g. `php-build --prefix <prefix> <definition>`

- Should all the environment variables be available as options e.g.

  - `export PHP_BUILD_DEBUG=yes` or `--debug`
  - `export PHP_BUILD_DEFINITION_PATH=yes` or `--definitions-path <path>` 

  Should the environment variables override the options, or vice-versa?

- Rename `--pear` to `--with-pear` or `enable-pear`. If yes, should `--pear` only be deprecated?

- New options:
  - `--with-apache` or `--enable-apache` 
  - ... ???

**Comment by GrahamCampbell** [comment]
Stale.
